jenkins:
  nodes:
  - permanent:
      labelString: "test"
      launcher:
        inbound:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
      name: "test_node"
      remoteFS: "/usr/share/jenkins"
